import { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  ltr: "text-left",
  rtl: "text-right",
  heading: {
    h1: "scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl",
    h2: "scroll-m-20 border-b border-default-200 pb-2 text-3xl font-semibold tracking-tight first:mt-0",
    h3: "scroll-m-20 text-2xl font-semibold tracking-tight",
    h4: "scroll-m-20 text-xl font-semibold tracking-tight",
    h5: "scroll-m-20 text-lg font-semibold tracking-tight",
    h6: "scroll-m-20 text-base font-semibold tracking-tight",
  },
  paragraph: "leading-7 [&:not(:first-child)]:mt-6",
  quote: "mt-6 border-l-2 border-default-300 pl-6 italic text-default-700",
  link: "text-primary hover:underline hover:cursor-pointer",
  list: {
    checklist: "relative",
    listitem: "mx-8",
    listitemChecked:
      'relative mx-2 px-6 list-none outline-none line-through before:content-[""] before:w-4 before:h-4 before:top-0.5 before:left-0 before:cursor-pointer before:block before:absolute before:border before:border-primary before:rounded before:bg-primary after:content-[""] after:cursor-pointer after:border-white after:border-solid after:absolute after:block after:top-[6px] after:w-[3px] after:left-[7px] after:h-[6px] after:rotate-45 after:border-r-2 after:border-b-2',
    listitemUnchecked:
      'relative mx-2 px-6 list-none outline-none before:content-[""] before:w-4 before:h-4 before:top-0.5 before:left-0 before:cursor-pointer before:block before:absolute before:border before:border-default-400 before:rounded',
    nested: {
      listitem: "list-none before:hidden after:hidden",
    },
    ol: "m-0 p-0 list-decimal [&>li]:mt-2",
    olDepth: [
      "list-outside !list-decimal",
      "list-outside !list-[upper-roman]",
      "list-outside !list-[lower-roman]",
      "list-outside !list-[upper-alpha]",
      "list-outside !list-[lower-alpha]",
    ],
    ul: "m-0 p-0 list-outside [&>li]:mt-2",
    ulDepth: Array(5).fill("list-outside !list-disc"),
  },
  hashtag: "text-primary bg-primary-50 rounded-md px-1",
  text: {
    bold: "font-bold",
    code: "bg-default-100 px-1 py-0.5 rounded-md font-mono text-sm",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "sub",
    superscript: "sup",
    underline: "underline",
    underlineStrikethrough: "[text-decoration:underline_line-through]",
  },
  image: "relative inline-block select-none cursor-default",
  inlineImage: "relative inline-block select-none cursor-default",
  code: "bg-transparent font-mono block py-2 pl-12 pr-2 leading-[1.53] text-[13px] my-2 overflow-x-auto border border-default-300 relative rounded-lg [tab-size:2] before:content-[attr(data-gutter)] before:absolute before:bg-transparent before:border-r before:border-default-300 before:left-0 before:top-0 before:p-2 before:text-default-400 before:whitespace-pre-wrap before:text-right before:min-w-[25px]",
  codeHighlight: {
    atrule: "text-[#07a]",
    attr: "text-[#07a]",
    boolean: "text-[#905]",
    builtin: "text-[#690]",
    cdata: "text-default-400 italic",
    char: "text-[#690]",
    class: "text-[#dd4a68]",
    "class-name": "text-[#dd4a68]",
    comment: "text-default-400 italic",
    constant: "text-[#905]",
    deleted: "text-[#905]",
    doctype: "text-default-400 italic",
    entity: "text-[#9a6e3a]",
    function: "text-[#dd4a68]",
    important: "text-[#e90]",
    inserted: "text-[#690]",
    keyword: "text-[#07a]",
    namespace: "text-[#e90]",
    number: "text-[#905]",
    operator: "text-[#9a6e3a]",
    prolog: "text-default-400 italic",
    property: "text-[#905]",
    punctuation: "text-[#999]",
    regex: "text-[#e90]",
    selector: "text-[#690]",
    string: "text-[#690]",
    symbol: "text-[#905]",
    tag: "text-[#905]",
    url: "text-[#9a6e3a]",
    variable: "text-[#e90]",
  },
  table: "w-full border-collapse border-spacing-0 my-8 table-fixed",
  tableCell:
    "w-24 relative border border-default-300 px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right",
  tableCellActionButton:
    "bg-content1 block border-0 rounded-full w-5 h-5 text-foreground cursor-pointer shadow-sm",
  tableCellActionButtonContainer: "block right-1 top-1.5 absolute z-10 w-5 h-5",
  tableCellEditing: "rounded-sm shadow-inner bg-default-50",
  tableCellHeader:
    "bg-default-100 border border-default-300 px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right",
  tableCellPrimarySelected:
    "border-2 border-primary block h-[calc(100%-2px)] w-[calc(100%-2px)] absolute -left-[1px] -top-[1px] z-10 pointer-events-none",
  tableCellResizer:
    "absolute -right-1 h-full w-2 cursor-ew-resize z-10 top-0 hover:bg-primary/20 transition-colors",
  tableCellSelected: "bg-primary-50",
  tableCellSortedIndicator:
    "block opacity-50 absolute bottom-0 left-0 w-full h-1 bg-primary",
  tableResizeRuler: "block absolute w-[1px] h-full bg-primary top-0",
  tableRowStriping: "even:bg-default-50",
  tableSelected: "ring-2 ring-primary ring-offset-2",
  tableSelection: "bg-transparent",
  layoutItem: "border border-dashed border-default-300 px-4 py-2",
  layoutContainer: "grid gap-2.5 my-2.5 mx-0",
  autocomplete: "text-default-400",
  hr: "p-0.5 border-none my-1 mx-0 cursor-pointer after:content-[''] after:block after:h-0.5 after:bg-default-200 selected:ring-2 selected:ring-primary selected:ring-offset-2",
  embedBlock: {
    base: "select-none",
    focus: "ring-2 ring-primary ring-offset-2",
  },
  indent: "[--lexical-indent-base-value:40px]",
};
