import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types ./src/lib/appwrite/appwrite.ts`.

export enum UnitsPeriodAfterOpeningUnit {
    MONTHS = "months",
    YEARS = "years"
}

export enum RegimentsType {
    MORNING = "morning",
    NIGHT = "night"
}

export type Products = Models.Row & {
    name: string;
    brand: string;
    category: string;
    lastUsed: string | null;
    price: number;
    userId: string;
    rating: number | null;
    description: string | null;
    units: Units[];
    steps: Steps[];
    archivedAt: string | null;
    wishlistProducts: WishlistProducts[];
}

export type Units = Models.Row & {
    purchaseDate: string | null;
    expiresAt: string | null;
    periodAfterOpeningDuration: number | null;
    periodAfterOpeningUnit: UnitsPeriodAfterOpeningUnit | null;
    openedAt: string | null;
    paoExpiresAt: string | null;
    finishedAt: string | null;
    product: Products;
}

export type Routines = Models.Row & {
    userId: string;
    name: string;
    description: string | null;
    regiment: Regiments[];
}

export type Regiments = Models.Row & {
    type: RegimentsType;
    steps: Steps[];
    routine: Routines;
}

export type Steps = Models.Row & {
    name: string;
    description: string | null;
    products: Products[];
    regiment: Regiments;
}

export type WishlistProducts = Models.Row & {
    product: Products;
}
