import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types ./src/lib/appwrite/types.ts`.

export enum UnitsPeriodAfterOpeningUnit {
    MONTHS = "months",
    YEARS = "years"
}

export enum RegimentsType {
    MORNING = "morning",
    NIGHT = "night"
}

export enum ProfilesSkinType {
    OILY = "oily",
    DRY = "dry",
    COMBINATION = "combination",
    NORMAL = "normal"
}

export type Products = Models.Row & {
    name: string;
    brand: string;
    category: string;
    lastUsed: string | null;
    price: number;
    userId: string;
    rating: number | null;
    description: string | null;
    units: Units[];
    steps: Steps[];
    archivedAt: string | null;
    wishlistProducts: WishlistProducts[];
    catalogBrand: Brands;
    catalogProduct: CatalogProducts;
}

export type Units = Models.Row & {
    purchaseDate: string | null;
    expiresAt: string | null;
    periodAfterOpeningDuration: number | null;
    periodAfterOpeningUnit: UnitsPeriodAfterOpeningUnit | null;
    openedAt: string | null;
    paoExpiresAt: string | null;
    finishedAt: string | null;
    product: Products;
}

export type Routines = Models.Row & {
    userId: string;
    name: string;
    description: string | null;
    regiment: Regiments[];
}

export type Regiments = Models.Row & {
    type: RegimentsType;
    steps: Steps[];
    routine: Routines;
}

export type Steps = Models.Row & {
    name: string;
    description: string | null;
    products: Products[];
    regiment: Regiments;
}

export type WishlistProducts = Models.Row & {
    product: Products;
    userId: string;
    name: string | null;
    deletedAt: string | null;
}

export type Profiles = Models.Row & {
    hasSensitiveSkin: boolean | null;
    skinType: ProfilesSkinType | null;
    skinIssues: string[] | null;
    userId: string;
}

export type Brands = Models.Row & {
    name: string;
    website: string | null;
    logoUrl: string | null;
    products: CatalogProducts[];
    userProducts: Products[];
}

export type CatalogProducts = Models.Row & {
    name: string;
    brand: Brands;
    category: string | null;
    imageUrl: string | null;
    description: string | null;
    userProducts: Products[];
}
